apiVersion: v1
kind: Secret
metadata:
  name: nexus-credentials
type: Opaque
data:
  NEXUS_URL: aHR0cDovL25leHVzLWxpYi5haWR0YWFzLmNvbTo4MDgxL3JlcG9zaXRvcnkvcmVsZWFzZXM= 
  NEXUS_USERNAME: YWRtaW4=  
  NEXUS_PASSWORD: TW9iaXVzI15QcjBkRCNwTDA5NypYUw==

